spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.117.156.226:3306/counsel
    username: ubuntu
    password: Software_64

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 20
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        spring.redis.jedis.pool.min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 1000

wx:
  appId: wx418a58e02xxx
  appSecret: 9ff73d06c24154a1854999ea6exxx
#  appId: wx548a99cf2b5xxx
#  appSecret: 20045ded4b565219e4d7116f01dxxxx

im:
  sdkAppId: 140081xxx
  secretKey: 09c3165c7f23871cdbef8f6db600ae2c59ee44b4628b44f7f6896a6xxxx

tencent:
  msm:
    id: AKIDc3GDvObaVBcnjRsDKJ3LOhkY6OQEpAH9xxx
    secret: e2kDQN4XkL3zg7IEvPdbOzKPGuhPuCI9xxx
    appId: 1400826946
    signName: 个人Java开发技术分享
    templateId: 1820500
